///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SporGolf {
/*
{
  "stadium": "Riviera Country  Club",
  "country": "United States of America",
  "region": "",
  "tournament": "The Genesis Invitational Round 2",
  "start": "2023-02-17 19:20",
  "match": "Kelly Kraft, Taylor Montgomery, Kevin Streelman"
} 
*/

  String? stadium;
  String? country;
  String? region;
  String? tournament;
  String? start;
  String? match;

  SporGolf({
    this.stadium,
    this.country,
    this.region,
    this.tournament,
    this.start,
    this.match,
  });
  SporGolf.fromJson(Map<String, dynamic> json) {
    stadium = json['stadium']?.toString();
    country = json['country']?.toString();
    region = json['region']?.toString();
    tournament = json['tournament']?.toString();
    start = json['start']?.toString();
    match = json['match']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['stadium'] = stadium;
    data['country'] = country;
    data['region'] = region;
    data['tournament'] = tournament;
    data['start'] = start;
    data['match'] = match;
    return data;
  }
}

class SporCricket {
/*
{
  "stadium": "Feroz Shah Kotla, Delhi",
  "country": "India",
  "region": "",
  "tournament": "India v Australia Test Series 2023",
  "start": "2023-02-17 04:00",
  "match": "India v Australia"
} 
*/

  String? stadium;
  String? country;
  String? region;
  String? tournament;
  String? start;
  String? match;

  SporCricket({
    this.stadium,
    this.country,
    this.region,
    this.tournament,
    this.start,
    this.match,
  });
  SporCricket.fromJson(Map<String, dynamic> json) {
    stadium = json['stadium']?.toString();
    country = json['country']?.toString();
    region = json['region']?.toString();
    tournament = json['tournament']?.toString();
    start = json['start']?.toString();
    match = json['match']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['stadium'] = stadium;
    data['country'] = country;
    data['region'] = region;
    data['tournament'] = tournament;
    data['start'] = start;
    data['match'] = match;
    return data;
  }
}

class SporFootball {
/*
{
  "stadium": "Rkc Waalwijk",
  "country": "Netherlands",
  "region": "",
  "tournament": "Dutch Eredivisie",
  "start": "2023-02-17 19:00",
  "match": "RKC Waalwijk vs Fortuna Sittard"
} 
*/

  String? stadium;
  String? country;
  String? region;
  String? tournament;
  String? start;
  String? match;

  SporFootball({
    this.stadium,
    this.country,
    this.region,
    this.tournament,
    this.start,
    this.match,
  });
  SporFootball.fromJson(Map<String, dynamic> json) {
    stadium = json['stadium']?.toString();
    country = json['country']?.toString();
    region = json['region']?.toString();
    tournament = json['tournament']?.toString();
    start = json['start']?.toString();
    match = json['match']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['stadium'] = stadium;
    data['country'] = country;
    data['region'] = region;
    data['tournament'] = tournament;
    data['start'] = start;
    data['match'] = match;
    return data;
  }
}

class Spor {
/*
{
  "football": [
    {
      "stadium": "Rkc Waalwijk",
      "country": "Netherlands",
      "region": "",
      "tournament": "Dutch Eredivisie",
      "start": "2023-02-17 19:00",
      "match": "RKC Waalwijk vs Fortuna Sittard"
    }
  ],
  "cricket": [
    {
      "stadium": "Feroz Shah Kotla, Delhi",
      "country": "India",
      "region": "",
      "tournament": "India v Australia Test Series 2023",
      "start": "2023-02-17 04:00",
      "match": "India v Australia"
    }
  ],
  "golf": [
    {
      "stadium": "Riviera Country  Club",
      "country": "United States of America",
      "region": "",
      "tournament": "The Genesis Invitational Round 2",
      "start": "2023-02-17 19:20",
      "match": "Kelly Kraft, Taylor Montgomery, Kevin Streelman"
    }
  ]
} 
*/

  List<SporFootball?>? football;
  List<SporCricket?>? cricket;
  List<SporGolf?>? golf;

  Spor({
    this.football,
    this.cricket,
    this.golf,
  });
  Spor.fromJson(Map<String, dynamic> json) {
    if (json['football'] != null) {
      final v = json['football'];
      final arr0 = <SporFootball>[];
      v.forEach((v) {
        arr0.add(SporFootball.fromJson(v));
      });
      football = arr0;
    }
    if (json['cricket'] != null) {
      final v = json['cricket'];
      final arr0 = <SporCricket>[];
      v.forEach((v) {
        arr0.add(SporCricket.fromJson(v));
      });
      cricket = arr0;
    }
    if (json['golf'] != null) {
      final v = json['golf'];
      final arr0 = <SporGolf>[];
      v.forEach((v) {
        arr0.add(SporGolf.fromJson(v));
      });
      golf = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (football != null) {
      final v = football;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['football'] = arr0;
    }
    if (cricket != null) {
      final v = cricket;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['cricket'] = arr0;
    }
    if (golf != null) {
      final v = golf;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['golf'] = arr0;
    }
    return data;
  }
}
